spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentactionService
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
auth:
  strategy: jwt      # change to keycloak later

user:
  service:
    url: http://localhost:8081